name: dreamatlas2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.14
  - numpy=2.3.5
  - scipy=1.17.0
  - matplotlib=3.10.8
  - networkx=3.6.1
  - minorminer=0.2.21
  - ttkbootstrap=1.20.1
  - noise=1.2.2
  - numba=0.63.1
  - pillow=12.1.1
  - pip
  - pip:
      - dimod==0.12.21
      - dwave_networkx==0.8.18
      - fasteners==0.20
      - fonttools==4.61.1
      - homebase==1.0.1
      - iniconfig==2.3.0
      - kiwisolver==1.4.9
      - packaging==23.2
      - pluggy==1.6.0
      - Pygments==2.19.2
      - pyparsing==3.3.2
      - pytest==9.0.2
      - python-dateutil==2.9.0.post0
      - six==1.17.0
      - ttkthemes==3.3.0
